version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-rodrigoperes}"
    image: cyberbullying-data-prep
    platform: linux/amd64
    container_name: cyberbullying-data-prep-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-rodrigoperes}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-rodrigoperes}/.config/gcloud
    ports:
      - 8080:8080

    ipc: host
    init: true
